### PR TITLE
Add Number of Zendesk tickets in the past week to the dashboard

### PR DESCRIPTION
**Pull request by andyhd**

### CODE REVIEW

**Comment by s-block** [comment]
:+1:

**Comment by s-block** [comment]
Need to push change to 2nd-line-support-config repo with the three zendesk environment vars

**Comment by lukaszraczylo** [comment]
Okay, as soon as I'll have value for ZENDESK_TOKEN variable I'll be able to deploy changes in config repo :)

**Comment by lukaszraczylo** [comment]
Changes in config repo merged and live.

**Pull request merged**
